### ISSUE TITLE
Setting unknown property: marqu3s\behaviors\SaveGridPaginationBehavior::sessionPageSizeName

### ISSUE THREAD

**Issue by baldiri** [marqu3s/yii2-behaviors#4]
Hi,
i'm getting error mentioned in title, so i'm not sure what could be wrong in my config, let me show...

Yii version: 2.0.14.1, PHP version 7.0.16

Code in model:
```
public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created', 'modified'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['modified'],
                ],
                //if you're using datetime instead of UNIX timestamp:
                'value' => new Expression('NOW()'),
            ],
            'saveGridPage' =>[
                'class' => SaveGridPaginationBehavior::class,
                'sessionVarName' => self::class . 'GridPage',
                'sessionPageSizeName' => self::class . 'GridPageSize',
            ],
            'saveGridFilters' =>[
                'class' => SaveGridFiltersBehavior::class,
                'sessionVarName' => self::class . 'GridFilters',
            ]
        ];
    }
```
Code in ModelSearch:
```
public function search($params)
    {
        //$pageSize = isset($params['per-page']) ? intval($params['per-page']) : 50;

        $query = Product::find();

        // add conditions that should always apply here
        $query->joinWith(['category', 'attachment']);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            //'pagination' => ['pageSize' => $pageSize],
            'pagination' => [
                'page' => $this->getGridPage(),
                'pageSize' => $this->getGridPageSize(),
            ],
        ]);

        $dataProvider = $this->loadWithFilters($params, $dataProvider); // From SaveGridFiltersBehavior
        ...
        return $dataProvider;
    }
```
From degug gii module i get:
```
yii\base\UnknownPropertyException: Setting unknown property: marqu3s\behaviors\SaveGridPaginationBehavior::sessionPageSizeName in /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php:163
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\BaseObject->__set('sessionPageSize...', 'app\\models\\Prod...')
#1 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(marqu3s\behaviors\SaveGridPaginationBehavior), Array)
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /var/www/html/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#4 /var/www/html/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('marqu3s\\behavio...', Array, Array)
#5 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('marqu3s\\behavio...', Array, Array)
#6 /var/www/html/vendor/yiisoft/yii2/base/Component.php(749): yii\BaseYii::createObject(Array)
#7 /var/www/html/vendor/yiisoft/yii2/base/Component.php(733): yii\base\Component->attachBehaviorInternal('saveGridPage', Array)
#8 /var/www/html/vendor/yiisoft/yii2/base/Component.php(602): yii\base\Component->ensureBehaviors()
#9 /var/www/html/vendor/yiisoft/yii2/db/BaseActiveRecord.php(924): yii\base\Component->trigger('init')
#10 /var/www/html/models/Product.php(65): yii\db\BaseActiveRecord->init()
#11 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): app\models\Product->init()
#12 /var/www/html/controllers/ProductController.php(105): yii\base\BaseObject->__construct()
#13 [internal function]: app\controllers\ProductController->actionIndex()
#14 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('index', Array)
#17 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('product/index', Array)
#18 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#19 /var/www/html/web/index.php(12): yii\base\Application->run()
#20 {main}
```
Any ideas?¿? Thanks a lot in advance!!!

**Comment by marqu3s** [comment]
Check the new commit please.

**Comment by baldiri** [comment]
Hi @marqu3s,

i still get same error. 
About 'saveGridFilters' behavior works ok, but 'saveGridPage' still not in my code.

Thanks any way!!!
